const Products = [
    {
    id: 1,
    img: "images/ebi_sushi.jpg",
    title: "Sushi Ebi (3 pcs.)",
    category: "Sushi",
    price: 10,
    compound: "Sushi rice, tiger shrimp.",
    },
    {
    id: 2,
    img: "images/sake_sushi.jpg",
    title: "Sushi Sake (3 pcs.)",
    category: "Sushi",
    price: 8,
    compound: "Sushi rice, salmon.",
    }, 
    {
    id: 3,
    img: "images/roll-filadelfija-medium-rectangular-b95e4f9fa26c44a19031670e448374fa.jpeg",
    title: "Philadelphia roll", 
    category: "Rolls",
    price: 11,
    compound: "Sushi rice, cucumber, cream cheese, nori leaf.",  
    },
    {
    id: 4,
    img: "images/zapechennyjj-roll-s-lososem-medium-rectangular-764a91ea6d4f4323bc017312e8503621.jpeg",
    title: "Baked roll",
    category: "Rolls",
    price: 13,
    compound: "Sushi rice, nori, salmon, baked sauce.",  
    },   
    {
    id: 5,
    img: "images/zapechennyjj-roll-s-bekonom-medium-rectangular-b1313fffb4b14b178c0f3e3ade09248d.jpeg",
    title: "Unagi roll dragon",
    category: "Rolls",
    price: 12,
    compound: "Sushi rice, nori, salmon, cheese, cucumber, eel, sesame seeds, unagi sauce.", 
    },
    {
    id: 6,
    img: "images/maki-s-ogurcom-medium-rectangular-fc82b91f9d61471d98f28ed367c5bfd3.jpeg",
    title: "Roll syake maki with cucumber",
    category: "Rolls",
    price: 6,
    compound: "Sushi rice, nori, cucumber.",
    },
    {
    id: 7,
    img: "images/maki-s-tuncom-medium-rectangular-5ba382fa55c64cde940c56f147d23a17.jpeg",
    title: "Fish roll",
    category: "Rolls",
    price: 7,
    compound: "Sushi rice, nori, tuna.", 
    },
    {
    id: 8,
    img: "images/roll-kalifornija-medium-rectangular-79889a88d972498a9abd5717a4a081a0.jpeg",
    title: "California roll",
    category: "Rolls",
    price: 13,
    compound: "Sushi rice, mirin, cucumber, crab meat, tobiko caviar, dry nori seaweed.", 
    },
    {
    id: 9,
    img: "images/zapechennyjj-roll-s-ugrem-medium-rectangular-6571718da8d54c5fae1d71e8aeb967f9.jpeg",
    title: "Baked eel roll",
    category: "Rolls",
    price: 14,
    compound: "Sushi rice, unagi, nori, unagi sauce, cucumber, sesame seeds", 
    },
    {
    id: 10,
    img: "images/zapechennyjj-shichimi-roll-s-krevetkojj-medium-rectangular-bcdb65ebc86f4ba094edbda2dc5b4dd7.jpeg",
    title: "Baked roll with tiger shrimp",
    category: "Rolls",
    price: 15,
    compound: "Sushi rice, tiger shrimp, salmon, Dutch cheese, tobiko, spice sauce, sesame. ", 
    },
    {
    id: 11,
    img: "images/roll-s-tuncom-i-krevetkojj-medium-rectangular-f4ab4c29d3cc473ba61e0dcc4676021d.jpeg",
    title: "Tempura roll with shrimp",
    category: "Rolls",
    price: 13,
    compound: "Sushi rice, preprepared frozen shrimp tempura, English cucumber, Just-ripe avocado.", 
    },
    {
    id: 12,
    img: "images/boul-s-lososem-medium-rectangular-fc63ba26b2604a999a2b1c264c5932fc.jpeg",
    title: "Bowl with salmon",
    category: "Poke",
    price: 15,
    compound: "Atlantic Salmon (Salmon), quinoa cooked, tomato (tomato) greenhouse, seaweed agar, dried greenhouse cucumber, olive oil, sesame oil, raw ginger root, soy sauce, reduced sodium", 
    },
    {
    id: 13,
    img: "images/boul-vegetarianskijj-medium-rectangular-cfe2cb81c6cb4d9780c6add05ceb0a16.jpeg",
    title: "Vegetarian bowle",
    category: "Poke",
    price: 12,
    compound: "Boiled rice, tofu cheese, edamame beans, tomatoes, chuka seaweed, wakame seaweed, walnut sauce, hoisin sauce, green onion, white sesame.", 
    },
    {
    id: 14,
    img: "images/boul-s-govjadinojj-medium-rectangular-cee370be95894b19b6058281566fbce0.jpeg",
    title: "Bowl with beef",
    category: "Poke",
    price: 16,
    compound: "Boiled rice, beef, kimchi cabbage (Chinese cabbage, rice vinegar, leek, carrot, sriracha sauce, sugar, garlic, salt, shichimi spice), edamame beans, teriyaki sauce, hoisin sauce, sunflower oil, green onion, white sesame.",
    },
    {
    id: 15,
    img: "images/boul-s-tuncom-medium-rectangular-b63bbda58f394d30ad92eb828425e284.jpeg",
    title: "Bowl with tuna",
    category: "Poke",
    price: 15,
    compound: "Tuna, edamame beans, chuka seaweed, rice, walnut sauce, sesame seeds, green onions, Thai sauce.",
    },
    {
    id: 16,
    img: "images/shaverma-boul-medium-rectangular-8d9faa4aa96f4815801d480c9790ce3f.jpeg",
    title: "Shaverma Bowl",
    category: "Poke",
    price: 12,
    compound: "Chicken, Idaho potatoes, tomatoes, cucumber, Chinese cabbage, pickled red onion (red onion, vinegar, sugar, dill), shawarma sauce (sour cream, mayonnaise, fresh garlic, spices).",
    },
    {
    id: 17,
    img: "images/Second set.jpg",
    title: "Daily Set",
    category: "Sets",
    price: 50,
    compound: "- Green Salmon Klasik (1 rolnica) - Losos, avokado, Naked Salmon (1 rolnica) - Losos, krastavac, Salmon Nigiri (2 kom), Miso Klasik",
    },
    {
    id: 18,
    img: "images/Third set.jpg",
    title: "Solomoon",
    category: "Sets",
    price: 60,
    compound: "- Crunchy Classic (1 roll) - Salmon, feta cheese, paprika, Verde Fumé (1 roll) - Smoked salmon, cream cheese, cucumber, dill, Salmon Cali (1 roll) - Salmon, avocado, cucumber, sesame, Spicy Tuna Classic (1 roll) - Spicy tuna, crispy onions, sriracha, Mango Exotic (1 roll) - Mango, gambor tempura, coconut, cucumber, mango sauce, Flambo Salmon (1 roll) - Flambé salmon, yakitori sauce, gambor, chives, aioli, dried tomatoes, sesame, Curly Nigiri (2 pcs), Red Power Nigiri (2 pcs), Eel Nigiri (2 pcs), Salmon Nigiri (2 pcs), Miso Classic",
    },
    {
    id: 19,
    img: "images/Fourth set.jpg",
    title: "Feast of Taste",
    category: "Sets",
    price: 80,
    compound: "- Cheesy Tuna Classic (1 roll) - Tuna, cream cheese, Salmon Cali (1 roll) - Salmon, avocado, cucumber, Gambor Nigiri (2 pcs.), Creamy Nigiri (2 pcs), Miso Classic",
    },
    {
    id: 20,
    img: "images/Fifth set.jpg",
    title: "Fusion",
    category: "Sets",
    price: 30,
    compound: "- Salmon Cali (1 roll / 6 pcs.) - Salmon, avocado, cucumber, sesame, Cucumber Roll (1 roll / 6 pcs.) - Cucumber, Salmon Nigiri (3 pieces) - Salmon, Spring Rolls Veggie (1 piece), Edamame",
    },
    {
    id: 21,
    img: "images/sixth set.jpg",
    title: "Unagi Set",
    category: "Sets",
    price: 29,
    compound: "California Eel (8 pieces) - tobiko, avocado, cucumber, masago sauce, smoked eel, sesame, Philadelphia Eel (8 pieces) - Philadelphia cream cheese, avocado, tobiko, smoked eel, unagi sauce, sesame, Egulia and Tuna roll (8 pieces) - avocado, tuna, masago sauce, smoked eel, salmon caviar, unagi sauce, Zeleni Zmai roll (8 pieces) - avocado, masago sauce, salmon, eel, cucumber, unagi sauce, black and white sesame, Philadelphia Double Salmon (8 pieces) - Philadelphia cream cheese, salmon on top and inside the roll, salmon caviar",
    },
    {
    id: 22,
    img: "images/seventh set.jpg",
    title: "Discover",
    category: "Sets",
    price: 25,
    compound: "- Green Salmon Klasik (1 rolnica) - Losos, avokado, Naked Salmon (1 rolnica) - Losos, krastavac, Salmon Nigiri (2 kom), Miso Klasik",
    },
    {
    id: 23,
    img: "images/Eight set.jpg",
    title: "Perfect Mix",
    category: "Sets",
    price: 22,
    compound: "",
    },
    {
    id: 24,
    img: "images/Ninth set.jpg",
    title: "Lover",
    category: "Sets",
    price: 19,
    compound: "Philaclassic maki 8 шт, Cucumber maki 8 шт, Avokado maki 8 шт, Sakecheese maki 8 шт",
    },
    {
    id: 25,
    img: "images/redbull.JPG",
    title: "Red Bull",
    category: "Drinks",
    price: 4,
    compound: "Red Bull",
    },
    {
    id: 26,
    img: "images/cola.JPG",
    title: "Coka Cola",
    category: "Drinks",
    price: 2,
    compound: "Coka Cola",
    },
    {
    id: 27,
    img: "images/Corona.jpg",
    title: "Corona Extra",
    category: "Drinks",
    price: 3,
    compound: "Svetli lager",
    },
    {
    id: 28,
    img: "images/Stella.jpg",
    title: "Stella Artois",
    category: "Drinks",
    price: 1,
    compound: "Svetli lager",
    },
    {
    id: 29,
    img: "images/Weihenstephane.jpg",
    title: "Veihenstephaner",
    category: "Drinks",
    price: 2,
    compound: "Light lager",
    },
    {
    id: 30,
    img: "images/First wine.jpg",
    title: "Scuderia Italia Chianti 2012",
    category: "Drinks",
    price: 99,
    compound: "Red Wine",
    },
    {
    id: 31,
    img: "images/Second wine.jpg",
    title: "Scuderia Italia 2011",
    category: "Drinks",
    price: 129,
    compound: "Red Wine",
    }
]
export default Products;
